### ISSUE TITLE
Your web app is ready! 🚀

### ISSUE THREAD

**Issue by sleepingexperiments** [MJ12358/flutter-widgetz#1]
Hey! 👋

Someone has requested a demo of your project using [Ukoreh](https://ukoreh.fun/)! 🧙‍♂️.

The app compiled fine and is now live at https://flutter-preview.github.io/MJ12358-flutter-widgetz

**Comment by MJ12358** [comment]
@sleepingexperiments You have been reported to GitHub for spam.
